[book]
title        = "变向能力场地测试在足球助理裁判员中的适用性"
authors      = ["zz"]
language     = "zh"
multilingual = false
src = "src"

[output.html]
mathjax-support = true
git-repository-url = "https://zzzxj12138.github.io/03/"